ANALYZERS = [
    {
        "id": "abbott-cell-dyn-ruby-01",
        "name": "CELL-DYN Ruby",
        "vendor": "Abbott",
        "protocol": "HL7",
        "transport": "MLLP",
        "listenPort": 5001,
        "resultDestinationHost": "localhost",
        "resultDestinationPort": 2575,
        "supportedTests": ["CBC", "WBC", "RBC", "HGB", "HCT", "MCV", "MCH", "MCHC", "PLT", "LYM%", "MID%", "GRA%"],
    },
    {
        "id": "sysmex-xn-1000-01",
        "name": "XN-1000",
        "vendor": "Sysmex",
        "protocol": "HL7",
        "transport": "MLLP",
        "listenPort": 5002,
        "resultDestinationHost": "localhost",
        "resultDestinationPort": 2575,
        "supportedTests": ["CBC", "WBC", "RBC", "HGB", "HCT", "PLT", "NEUT%", "LYMPH%", "MONO%", "EO%", "BASO%", "NRBC", "RET"],
    },
    {
        "id": "abbott-architect-ci4100-01",
        "name": "ARCHITECT ci4100",
        "vendor": "Abbott",
        "protocol": "HL7",
        "transport": "MLLP",
        "listenPort": 5003,
        "resultDestinationHost": "localhost",
        "resultDestinationPort": 2575,
        "supportedTests": ["GLU", "CREA", "UREA", "ALT", "AST", "CHOL", "TRIG", "TSH", "T3", "T4", "HBsAg", "HIV"],
    },
    {
        "id": "sysmex-uc-3500-01",
        "name": "UC-3500",
        "vendor": "Sysmex",
        "protocol": "ASTM",
        "transport": "TCP_SIMULATED",
        "listenPort": 5004,
        "resultDestinationHost": "localhost",
        "resultDestinationPort": 2575,
        "supportedTests": ["GLU", "PRO", "BLD", "LEU", "NIT", "KET", "BIL", "URO", "pH", "SG", "ALB", "CRE"],
    },
    {
        "id": "generic-hl7-01",
        "name": "Equipo generico HL7",
        "vendor": "Generic",
        "protocol": "HL7",
        "transport": "MLLP",
        "listenPort": 5010,
        "resultDestinationHost": "localhost",
        "resultDestinationPort": 2575,
        "supportedTests": ["CBC", "GLU", "CREA", "ALT", "AST"],
    },
    {
        "id": "generic-astm-01",
        "name": "Equipo generico ASTM",
        "vendor": "Generic",
        "protocol": "ASTM",
        "transport": "TCP_SIMULATED",
        "listenPort": 5011,
        "resultDestinationHost": "localhost",
        "resultDestinationPort": 2575,
        "supportedTests": ["GLU", "PRO", "BLD", "LEU", "NIT"],
    },
]


TEST_PROFILES = {
    "WBC": {"unit": "10^3/uL", "low": 4.0, "high": 10.0, "decimals": 1},
    "RBC": {"unit": "10^6/uL", "low": 4.2, "high": 5.9, "decimals": 2},
    "HGB": {"unit": "g/dL", "low": 12.0, "high": 17.5, "decimals": 1},
    "HCT": {"unit": "%", "low": 36.0, "high": 52.0, "decimals": 1},
    "MCV": {"unit": "fL", "low": 80.0, "high": 100.0, "decimals": 1},
    "MCH": {"unit": "pg", "low": 27.0, "high": 33.0, "decimals": 1},
    "MCHC": {"unit": "g/dL", "low": 32.0, "high": 36.0, "decimals": 1},
    "PLT": {"unit": "10^3/uL", "low": 150, "high": 450, "decimals": 0},
    "LYM%": {"unit": "%", "low": 20.0, "high": 45.0, "decimals": 1},
    "MID%": {"unit": "%", "low": 2.0, "high": 12.0, "decimals": 1},
    "GRA%": {"unit": "%", "low": 45.0, "high": 75.0, "decimals": 1},
    "NEUT%": {"unit": "%", "low": 40.0, "high": 75.0, "decimals": 1},
    "LYMPH%": {"unit": "%", "low": 20.0, "high": 45.0, "decimals": 1},
    "MONO%": {"unit": "%", "low": 2.0, "high": 10.0, "decimals": 1},
    "EO%": {"unit": "%", "low": 0.0, "high": 6.0, "decimals": 1},
    "BASO%": {"unit": "%", "low": 0.0, "high": 2.0, "decimals": 1},
    "NRBC": {"unit": "/100WBC", "low": 0.0, "high": 0.2, "decimals": 1},
    "RET": {"unit": "%", "low": 0.5, "high": 2.5, "decimals": 1},
    "GLU": {"unit": "mg/dL", "low": 70, "high": 110, "decimals": 0},
    "CREA": {"unit": "mg/dL", "low": 0.6, "high": 1.3, "decimals": 2},
    "UREA": {"unit": "mg/dL", "low": 10, "high": 45, "decimals": 0},
    "ALT": {"unit": "U/L", "low": 7, "high": 56, "decimals": 0},
    "AST": {"unit": "U/L", "low": 10, "high": 40, "decimals": 0},
    "CHOL": {"unit": "mg/dL", "low": 120, "high": 200, "decimals": 0},
    "TRIG": {"unit": "mg/dL", "low": 50, "high": 150, "decimals": 0},
    "TSH": {"unit": "uIU/mL", "low": 0.4, "high": 4.0, "decimals": 2},
    "T3": {"unit": "ng/dL", "low": 80, "high": 180, "decimals": 0},
    "T4": {"unit": "ug/dL", "low": 5.0, "high": 12.0, "decimals": 1},
    "HBsAg": {"unit": "S/CO", "low": 0.0, "high": 0.9, "decimals": 2},
    "HIV": {"unit": "S/CO", "low": 0.0, "high": 0.9, "decimals": 2},
    "PRO": {"unit": "mg/dL", "low": 0, "high": 15, "decimals": 0},
    "BLD": {"unit": "Ery/uL", "low": 0, "high": 5, "decimals": 0},
    "LEU": {"unit": "Leu/uL", "low": 0, "high": 10, "decimals": 0},
    "NIT": {"unit": "pos/neg", "low": 0, "high": 0, "decimals": 0},
    "KET": {"unit": "mg/dL", "low": 0, "high": 5, "decimals": 0},
    "BIL": {"unit": "mg/dL", "low": 0, "high": 0.2, "decimals": 1},
    "URO": {"unit": "mg/dL", "low": 0.2, "high": 1.0, "decimals": 1},
    "pH": {"unit": "", "low": 5.0, "high": 8.0, "decimals": 1},
    "SG": {"unit": "", "low": 1.005, "high": 1.030, "decimals": 3},
    "ALB": {"unit": "mg/L", "low": 0, "high": 30, "decimals": 0},
}


def analyzer_by_id(analyzer_id: str) -> dict | None:
    return next((item for item in ANALYZERS if item["id"] == analyzer_id), None)
